/* ============================================================
   repos-data.js — single source of truth for ALL community repos
   Add a repo  ->  add ONE object to REPOS below.
   - owner/repo : drives the GitHub link AND the card image (auto)
   - cats       : array of category ids (a repo can be in several)
   - stars      : a NUMBER (e.g. 35000) — formatted for display automatically
   - featured   : true  -> shows on the main page top-3
   ============================================================ */

const REPO_CATEGORIES = [
  { id: "ad", label: "Active Directory" },
  { id: "anonymity", label: "Anonymity & Privacy" },
  { id: "api", label: "API Security" },
  { id: "automotive", label: "Automotive & CAN" },
  { id: "pwn", label: "Binary Exploitation (Pwn)" },
  { id: "blue", label: "Blue Team / Defensive" },
  { id: "bluetooth", label: "Bluetooth & BLE" },
  { id: "c2", label: "C2 Frameworks" },
  { id: "cheatsheets", label: "Cheatsheets & Resources" },
  { id: "cloud", label: "Cloud & Container" },
  { id: "cms", label: "CMS Scanning" },
  { id: "crypto", label: "Cryptography" },
  { id: "devsecops", label: "DevSecOps / CI-CD" },
  { id: "dns", label: "DNS" },
  { id: "dos", label: "DoS & Stress Testing" },
  { id: "email", label: "Email & SMTP" },
  { id: "evasion", label: "Evasion (AV / EDR)" },
  { id: "exploit", label: "Exploitation" },
  { id: "exploitdev", label: "Exploit Development" },
  { id: "forensics", label: "Forensics & DFIR" },
  { id: "frameworks", label: "Frameworks (All-in-One)" },
  { id: "fuzzing", label: "Fuzzing" },
  { id: "hardware", label: "Hardware Hacking" },
  { id: "ics", label: "ICS / SCADA / OT" },
  { id: "iot", label: "IoT" },
  { id: "lateral", label: "Lateral Movement" },
  { id: "malware", label: "Malware Analysis" },
  { id: "misc", label: "Misc / Utilities" },
  { id: "mobile", label: "Mobile" },
  { id: "network", label: "Networking & MITM" },
  { id: "osint", label: "OSINT" },
  { id: "passwords", label: "Password Attacks" },
  { id: "persistence", label: "Persistence" },
  { id: "phishing", label: "Phishing" },
  { id: "post", label: "Post-Exploitation" },
  { id: "privesc", label: "Privilege Escalation" },
  { id: "proxy", label: "Proxies & Interception" },
  { id: "purple", label: "Purple Team" },
  { id: "recon", label: "Recon & Scanning" },
  { id: "redteam", label: "Red Team Ops" },
  { id: "reporting", label: "Reporting" },
  { id: "re", label: "Reverse Engineering" },
  { id: "rfid", label: "RFID & NFC" },
  { id: "sdr", label: "SDR / Radio" },
  { id: "sniffing", label: "Sniffing & Spoofing" },
  { id: "social", label: "Social Engineering" },
  { id: "steg", label: "Steganography" },
  { id: "threatintel", label: "Threat Intelligence" },
  { id: "training", label: "Labs & Training" },
  { id: "tunneling", label: "Tunneling & Pivoting" },
  { id: "vulnscan", label: "Vulnerability Scanning" },
  { id: "web", label: "Web App" },
  { id: "web3", label: "Web3 / Smart Contracts" },
  { id: "wireless", label: "Wireless / WiFi" },
  { id: "wordlists", label: "Wordlists & Payloads" },
];

/* Star counts are approximate snapshots — refresh them with the
   optional GitHub-API script (see the chat notes). */
const REPOS = [
  {
    owner: "rapid7",
    repo: "metasploit-framework",
    lang: "Ruby",
    stars: 38419,
    featured: true,
    cats: ["exploit", "post", "frameworks", "exploitdev"],
    desc: "The exploitation framework — exploits, payloads, post-ex. MCP-integrated on the box.",
  },
  {
    owner: "danielmiessler",
    repo: "SecLists",
    lang: "PHP",
    stars: 71599,
    featured: true,
    cats: ["wordlists"],
    desc: "The security tester's companion — usernames, passwords, payloads, fuzzing lists.",
  },
  {
    owner: "projectdiscovery",
    repo: "nuclei",
    lang: "Go",
    stars: 29194,
    featured: true,
    cats: ["vulnscan", "recon", "web"],
    desc: "Fast, template-based vulnerability scanner. Huge community template library.",
  },

  {
    owner: "nmap",
    repo: "nmap",
    lang: "C",
    stars: 13065,
    cats: ["recon", "network", "vulnscan"],
    desc: "The network mapper — host discovery, port scanning, service & OS detection.",
  },
  {
    owner: "sqlmapproject",
    repo: "sqlmap",
    lang: "Python",
    stars: 37676,
    cats: ["web", "exploit"],
    desc: "Automatic SQL injection detection and exploitation.",
  },
  {
    owner: "swisskyrepo",
    repo: "PayloadsAllTheThings",
    lang: "Python",
    stars: 78444,
    cats: ["wordlists", "web", "cheatsheets"],
    desc: "Payloads & bypasses for web app security — XSS, SQLi, SSRF, RCE.",
  },
  {
    owner: "carlospolop",
    repo: "PEASS-ng",
    lang: "Shell",
    stars: 20004,
    cats: ["privesc", "post"],
    desc: "LinPEAS / WinPEAS — privilege-escalation enumeration scripts.",
  },
  {
    owner: "bettercap",
    repo: "bettercap",
    lang: "Go",
    stars: 19426,
    cats: ["network", "sniffing", "wireless"],
    desc: "Swiss-army knife for network attacks — ARP/DNS spoofing, BLE, WiFi.",
  },
  {
    owner: "aircrack-ng",
    repo: "aircrack-ng",
    lang: "C",
    stars: 7297,
    cats: ["wireless", "passwords"],
    desc: "WiFi security auditing — WPA/WPA2 capture and cracking suite.",
  },
  {
    owner: "owasp-amass",
    repo: "amass",
    lang: "Go",
    stars: 14717,
    cats: ["recon", "osint", "dns"],
    desc: "In-depth attack-surface mapping and asset discovery.",
  },
  {
    owner: "projectdiscovery",
    repo: "subfinder",
    lang: "Go",
    stars: 13852,
    cats: ["recon", "osint", "dns"],
    desc: "Fast passive subdomain enumeration tool.",
  },
  {
    owner: "projectdiscovery",
    repo: "httpx",
    lang: "Go",
    stars: 10051,
    cats: ["recon"],
    desc: "Fast, multi-purpose HTTP toolkit for probing services.",
  },
  {
    owner: "ffuf",
    repo: "ffuf",
    lang: "Go",
    stars: 16246,
    cats: ["web", "recon", "fuzzing"],
    desc: "Fast web fuzzer — directories, vhosts, parameters.",
  },
  {
    owner: "OJ",
    repo: "gobuster",
    lang: "Go",
    stars: 13811,
    cats: ["recon", "web"],
    desc: "Directory, DNS and vhost busting tool written in Go.",
  },
  {
    owner: "SpecterOps",
    repo: "BloodHound",
    lang: "TypeScript",
    stars: 3121,
    cats: ["ad", "post", "recon"],
    desc: "Active Directory attack-path mapping using graph theory.",
  },
  {
    owner: "Pennyw0rth",
    repo: "NetExec",
    lang: "Python",
    stars: 5605,
    cats: ["ad", "post", "lateral"],
    desc: "Network execution tool (the maintained CrackMapExec successor).",
  },
  {
    owner: "hashcat",
    repo: "hashcat",
    lang: "C",
    stars: 26175,
    cats: ["passwords"],
    desc: "The world's fastest password recovery / GPU cracking tool.",
  },
  {
    owner: "openwall",
    repo: "john",
    lang: "C",
    stars: 13268,
    cats: ["passwords"],
    desc: "John the Ripper — versatile password cracker for many hash types.",
  },
  {
    owner: "vanhauser-thc",
    repo: "thc-hydra",
    lang: "C",
    stars: 11938,
    cats: ["passwords"],
    desc: "Fast login cracker — SSH, FTP, HTTP, SMB and 50+ protocols.",
  },
  {
    owner: "NationalSecurityAgency",
    repo: "ghidra",
    lang: "Java",
    stars: 69752,
    cats: ["re", "malware"],
    desc: "NSA's reverse-engineering framework — disassembly & decompilation.",
  },
  {
    owner: "radareorg",
    repo: "radare2",
    lang: "C",
    stars: 24123,
    cats: ["re", "malware"],
    desc: "Unix-like reverse-engineering framework and command-line toolset.",
  },
  {
    owner: "sherlock-project",
    repo: "sherlock",
    lang: "Python",
    stars: 85095,
    cats: ["osint"],
    desc: "Hunt down social-media accounts by username across platforms.",
  },
  {
    owner: "laramies",
    repo: "theHarvester",
    lang: "Python",
    stars: 16487,
    cats: ["osint", "recon", "email"],
    desc: "E-mails, subdomains and names harvester for early recon.",
  },
  {
    owner: "BishopFox",
    repo: "sliver",
    lang: "Go",
    stars: 11372,
    cats: ["c2", "post", "evasion", "redteam"],
    desc: "Adversary-emulation / C2 framework — cross-platform implants.",
  },
  {
    owner: "s0md3v",
    repo: "XSStrike",
    lang: "Python",
    stars: 15027,
    cats: ["web", "fuzzing"],
    desc: "Advanced XSS detection suite with smart payload generation.",
  },
  {
    owner: "maurosoria",
    repo: "dirsearch",
    lang: "Python",
    stars: 14399,
    cats: ["web", "recon"],
    desc: "Web path brute-forcer for content discovery.",
  },
  {
    owner: "volatilityfoundation",
    repo: "volatility3",
    lang: "Python",
    stars: 4191,
    cats: ["forensics", "malware"],
    desc: "Advanced memory-forensics framework.",
  },
  {
    owner: "wifiphisher",
    repo: "wifiphisher",
    lang: "Python",
    stars: 14632,
    cats: ["wireless", "phishing", "social"],
    desc: "Rogue access-point framework for red-team WiFi assessments.",
  },
  {
    owner: "hexsecteam",
    repo: "DroidHunter",
    lang: "Python",
    stars: 138,
    cats: ["mobile", "frameworks"],
    desc: "CLI-based Android security-assessment framework with a hacker-aesthetic terminal interface.",
  },
  {
    owner: "AzeemIdrisi",
    repo: "PhoneSploit-Pro",
    lang: "Python",
    stars: 5932,
    cats: ["mobile", "exploit", "post"],
    desc: "All-in-one tool to remotely exploit Android devices via ADB + Metasploit for a Meterpreter session.",
  },
  {
    owner: "ultrasecurity",
    repo: "Storm-Breaker",
    lang: "Python",
    stars: 5016,
    cats: ["social", "phishing", "osint"],
    desc: "Social-engineering toolkit — webcam, microphone and location access via crafted links.",
  },
  {
    owner: "Genymobile",
    repo: "scrcpy",
    lang: "C",
    stars: 143648,
    cats: ["mobile", "misc"],
    desc: "Mirror and control Android devices (video + audio) over USB or TCP/IP — no root needed.",
  },
  {
    owner: "trimstray",
    repo: "the-book-of-secret-knowledge",
    lang: "List",
    stars: 228689,
    cats: ["cheatsheets", "misc"],
    desc: "A huge collection of manuals, cheatsheets, one-liners, CLI/web tools and more.",
  },
  {
    owner: "Hack-with-Github",
    repo: "Awesome-Hacking",
    lang: "List",
    stars: 114522,
    cats: ["cheatsheets", "misc"],
    desc: "Curated awesome lists for hackers, pentesters and security researchers.",
  },
  {
    owner: "Z4nzu",
    repo: "hackingtool",
    lang: "Python",
    stars: 77525,
    cats: ["frameworks", "exploit", "misc"],
    desc: "All-in-one launcher bundling many common hacking tools.",
  },
  {
    owner: "WerWolv",
    repo: "ImHex",
    lang: "C++",
    stars: 53898,
    cats: ["re", "forensics"],
    desc: "A hex editor for reverse engineers and programmers — easy on the eyes at 3 AM.",
  },
  {
    owner: "x64dbg",
    repo: "x64dbg",
    lang: "C++",
    stars: 48652,
    cats: ["re", "malware", "exploitdev"],
    desc: "Open-source x64/x32 user-mode debugger for Windows — RE and malware analysis.",
  },
  // --- batch add ---
  {
    owner: "The-Art-of-Hacking",
    repo: "h4cker",
    lang: "Jupyter Notebook",
    stars: 27640,
    cats: ["cheatsheets", "training", "misc"],
    desc: "Massive collection of cybersecurity references, labs, tools and study material.",
  },
  {
    owner: "bee-san",
    repo: "Ciphey",
    lang: "Python",
    stars: 21454,
    cats: ["crypto", "forensics"],
    desc: "Automated decryption — detect and crack encodings, ciphers and hashes without keys.",
  },
  {
    owner: "bee-san",
    repo: "RustScan",
    lang: "Rust",
    stars: 19930,
    cats: ["recon", "network"],
    desc: "Ultra-fast modern port scanner that hands results straight to Nmap.",
  },
  {
    owner: "smicallef",
    repo: "spiderfoot",
    lang: "Python",
    stars: 18193,
    cats: ["osint", "recon", "threatintel"],
    desc: "OSINT automation — 200+ modules for footprinting and intelligence gathering.",
  },
  {
    owner: "vitalysim",
    repo: "Awesome-Hacking-Resources",
    lang: "List",
    stars: 17102,
    cats: ["cheatsheets", "training", "misc"],
    desc: "Curated collection of hacking and security learning resources.",
  },
  {
    owner: "sundowndev",
    repo: "hacker-roadmap",
    lang: "List",
    stars: 15404,
    cats: ["cheatsheets", "training", "recon"],
    desc: "A roadmap and toolkit reference for aspiring penetration testers.",
  },
  {
    owner: "Hacker0x01",
    repo: "hacker101",
    lang: "HTML",
    stars: 14449,
    cats: ["training", "web"],
    desc: "HackerOne's free educational web-security course and CTF material.",
  },
  {
    owner: "moonD4rk",
    repo: "HackBrowserData",
    lang: "Go",
    stars: 14205,
    cats: ["post", "passwords", "forensics"],
    desc: "Decrypt and export passwords, cookies, history and bookmarks from browsers.",
  },
  {
    owner: "HunxByts",
    repo: "GhostTrack",
    lang: "Python",
    stars: 14091,
    cats: ["osint"],
    desc: "Track username, phone number or IP location via OSINT sources.",
  },
  {
    owner: "mytechnotalent",
    repo: "Reverse-Engineering",
    lang: "C",
    stars: 13726,
    cats: ["re", "training", "exploitdev"],
    desc: "A free, comprehensive reverse-engineering tutorial from the ground up.",
  },
  {
    owner: "juice-shop",
    repo: "juice-shop",
    lang: "TypeScript",
    stars: 13351,
    cats: ["web", "training"],
    desc: "OWASP's intentionally insecure web app — the modern web-pentest playground.",
  },
  {
    owner: "digininja",
    repo: "DVWA",
    lang: "PHP",
    stars: 13233,
    cats: ["web", "training"],
    desc: "Damn Vulnerable Web Application — deliberately insecure PHP/MySQL practice target.",
  },
  {
    owner: "Datalux",
    repo: "Osintgram",
    lang: "Python",
    stars: 13185,
    cats: ["osint", "social"],
    desc: "Interactive OSINT tool for analysing Instagram accounts.",
  },
  {
    owner: "OWASP",
    repo: "mastg",
    lang: "Java",
    stars: 12973,
    cats: ["mobile", "cheatsheets", "training"],
    desc: "OWASP Mobile Application Security Testing Guide — the mobile pentest reference.",
  },
  {
    owner: "jopohl",
    repo: "urh",
    lang: "Python",
    stars: 12463,
    cats: ["sdr", "wireless", "re"],
    desc: "Universal Radio Hacker — capture, analyse and fuzz wireless protocols via SDR.",
  },
  {
    owner: "brannondorsey",
    repo: "wifi-cracking",
    lang: "List",
    stars: 12399,
    cats: ["wireless", "passwords", "cheatsheets"],
    desc: "Step-by-step guide to capturing and cracking WPA/WPA2 WiFi handshakes.",
  },
  {
    owner: "nahamsec",
    repo: "Resources-for-Beginner-Bug-Bounty-Hunters",
    lang: "List",
    stars: 12052,
    cats: ["training", "cheatsheets", "web"],
    desc: "Curated starting resources for getting into bug-bounty hunting.",
  },
  {
    owner: "k4m4",
    repo: "movies-for-hackers",
    lang: "List",
    stars: 11794,
    cats: ["misc"],
    desc: "A curated list of hacker-themed and tech movies.",
  },
  {
    owner: "HackTricks-wiki",
    repo: "hacktricks",
    lang: "List",
    stars: 11657,
    cats: ["cheatsheets", "privesc", "web", "post"],
    desc: "The legendary pentest methodology wiki — tricks for every phase of an engagement.",
  },
  {
    owner: "screetsec",
    repo: "TheFatRat",
    lang: "Shell",
    stars: 11273,
    cats: ["exploit", "evasion", "malware"],
    desc: "Payload and backdoor generator with AV-evasion features.",
  },
  {
    owner: "edoardottt",
    repo: "awesome-hacker-search-engines",
    lang: "List",
    stars: 10770,
    cats: ["osint", "recon", "cheatsheets"],
    desc: "Curated list of search engines useful for hackers, OSINT and recon.",
  },
  {
    owner: "infosecn1nja",
    repo: "Red-Teaming-Toolkit",
    lang: "List",
    stars: 10405,
    cats: ["redteam", "c2", "cheatsheets"],
    desc: "Curated red-team and adversary-simulation tooling, mapped to phases.",
  },
  {
    owner: "1N3",
    repo: "Sn1per",
    lang: "Shell",
    stars: 10185,
    cats: ["recon", "vulnscan", "frameworks"],
    desc: "Automated reconnaissance and attack-surface scanning framework.",
  },
  {
    owner: "samratashok",
    repo: "nishang",
    lang: "PowerShell",
    stars: 9951,
    cats: ["post", "redteam", "exploit"],
    desc: "Offensive PowerShell framework for pentesting and red teaming.",
  },
  {
    owner: "blacklanternsecurity",
    repo: "bbot",
    lang: "Python",
    stars: 9928,
    cats: ["recon", "osint", "vulnscan"],
    desc: "Recursive OSINT and attack-surface scanner built for automation.",
  },
  {
    owner: "OWASP",
    repo: "wstg",
    lang: "Python",
    stars: 9477,
    cats: ["web", "cheatsheets", "training"],
    desc: "OWASP Web Security Testing Guide — the definitive web-pentest methodology.",
  },
  {
    owner: "A-poc",
    repo: "RedTeam-Tools",
    lang: "List",
    stars: 8844,
    cats: ["redteam", "cheatsheets", "c2"],
    desc: "Curated red-team tools organised by attack phase.",
  },
  {
    owner: "jofpin",
    repo: "trape",
    lang: "Python",
    stars: 8701,
    cats: ["osint", "phishing", "social"],
    desc: "People-tracking and recon tool for OSINT investigations.",
  },
  {
    owner: "elder-plinius",
    repo: "CL4R1T4S",
    lang: "List",
    stars: 40614,
    cats: ["misc"],
    desc: "Transparency project collecting the system prompts of major AI tools.",
  },
  {
    owner: "elder-plinius",
    repo: "L1B3RT4S",
    lang: "List",
    stars: 19861,
    cats: ["misc"],
    desc: "Collection of LLM jailbreak / 'liberation' prompts for AI red-teaming.",
  },
];
/* expose for both pages */
window.REPO_CATEGORIES = REPO_CATEGORIES;
window.REPOS = REPOS;
